const ERRORS = {
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    NOT_ENOUGHT_DATA: 'NOT_ENOUGHT_DATA',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    THERE_IS_NO_LOGIN_SUBSTRING: 'THERE_IS_NO_LOGIN_SUBSTRING'
};

export { ERRORS };
